name: Antoine Barrault
description: Swift, iOS and some other stuffs
meta_description: "Swift,iOS and some other stuffs by Antoine Barrault"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://asapps.fr'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url: "http://asapps.fr" # the base hostname & protocol for your site
author: 'Antoine Barrault'

twitter_username: devasapps
github_username:  barrault01
